name: DEV/IT Build and Deployment Workflow

on:
 pull_request:
   branches: 
     - release/r*/dev   
     - release/r*/it   
   types: [closed]
jobs:
  DevITBuildPublishAndDeploy:
    uses: MuleyTestOrg/shared-runner-templates/.github/workflows/dev_it_workflow_template.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: 
      GH_SHARED_REPO_PAT: "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"
    
