name: Feature/HotFix Build Workflow

#Triggers workflow for feature and hotfix branches secrets added to the workflow
on:
  push:
    branches: 
      - feature/r*/* 
      - hotfix/r*/* 
jobs:
  FeatureHotfixBuildPackage:
    # Use this YAML in your workflow file for each job
    uses: MuleyTestOrg/shared-runner-templates/.github/workflows/feature_hotfix_workflow_template.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: 
      GH_SHARED_REPO_PAT: "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"
